site:
  production_url: "http://git.gelistiriciyiz.biz"
  title: "Git Püf Noktaları"
  subtitle: "Git ile ilgili Türkçe püf noktaları"
  tag_line: "Gündelik Hayatta GIT"
  description: "Git ile ilgili Türkçe püf noktaları"
  logo: "logo.png"
  cover_image: "cover.jpg"
  social:
    twitter: "GiT_Tips_TR"
    disqus: "gitgelistiriciyizbiz"
    google_analytics: "UA-6463685-39"
  company:
    name: "Geliştiriciyiz.biz"
    url: "http://gelistiriciyiz.biz/"
  product:
    name: "GELİŞTİRİCİYİZ.BİZ"
    url: "http://gelistiriciyiz.biz/"
  main_author:
    name: "Full Name"
    email: "email@example.com"
    link: "http://example.com"
    bio: "Title"
    twitter: "twitter_username"